data asgmt.case_alt4 (keep = PersonID Choice TOTTIME TOTCOST NumVeh ASC);
	array IVTT[2] IVTT_C IVTT_Tr;
	array OVTT[2] OVTT_C OVTT_Tr;
	array COST[2] COST_C COST_Tr;
	set asgmt.asgmt1_data;
	do i = 1 to 2;
		TOTTIME=IVTT[i]+OVTT[i];
		TOTCOST=COST[i];
		ASC=2-i;
		Choice=(Mode eq ASC);
		NumVeh=NumVeh*ASC;
		output;
	end;
run;
proc print data=asgmt.case_alt4 (obs=6);
run;
data asgmt.asgmt4_case (keep = PersonID Mode TIMEDIFF COSTDIFF NumVeh);
	set asgmt.asgmt1_data;
	TIMEDIFF=IVTT_Tr+OVTT_Tr-IVTT_C-OVTT_C;
	COSTDIFF=COST_Tr-COST_C;
run;
proc print data=asgmt.asgmt4_case (obs=3);
run;
data asgmt.asgmt4_case1 (keep = PersonID Mode TOTTIME TOTCOST NumVeh);
	set asgmt.asgmt1_data;
		if mode=1 then TOTTIME=IVTT_C+OVTT_C;
		else TOTTIME=IVTT_Tr+OVTT_Tr;
		if mode=1 then TOTCOST=COST_C;
		else TOTCOST=COST_Tr;
run;
proc means data=asgmt.asgmt4_case;
	var Mode TIMEDIFF COSTDIFF NumVeh;
run;
