data analysis;
	LR = -115.60281;
	LUR = -114.13818;
	LRT = -2*(LR - LUR);
	df = 1;
	p_value = 1 - probchi(LRT,df);
run;
proc print data=analysis;
	title1 "LR test statistic and p-value";
run;
data analysis;
	LR = -111.80399;
	LUR = -111.48638;
	LRT = -2*(LR - LUR);
	df = 2;
	p_value = 1 - probchi(LRT,df);
run;
proc print data=analysis;
	title1 "LR test statistic and p-value";
run;
data analysis;
	LR = -216.19685;
	LUR = -111.80399;
	LRT = -2*(LR - LUR);
	df = 3;
	p_value = 1 - probchi(LRT,df);
run;
proc print data=analysis;
	title1 "LR test statistic and p-value";
run;
