%let other = gender hhsize numveh nworkers nlicdriv hhinc transfer distance;
proc sort data=asgmt.asgmt1_data;
	by personID;
run;
data mode1;
	set asgmt.asgmt1_data;
	if mode=1 then mode1=0;
	else mode1=1;
run;
proc transpose data=mode1 out = data1(drop=_label_ _name_ rename=(col1=Mode));
	var mode mode1;
	by personID;
	copy &other;
run;
data data2;
	set data1;
	array a{8} &other;
	do i = 1 to 7;
	a{i} = coalesce(a{i},0);	
	end;
	drop i;
run;
data data3;
	set data2;
	retain _distance;
	if not missing(distance) then _distance=distance;
	else distance=_distance;
	drop _distance;
run;
