proc sort data=asgmt.data1;
	by personID;
run;
data mode1;
	set asgmt.data1;
	if mode=1 then mode1=0;
	else mode1=1;
run;
/* transpose mode ivtt ovtt cost */
proc transpose data=mode1 out = transpose_mode(drop=_label_ _name_ rename=(col1=Mode));
	var mode mode1;
	by personID;
run;
proc transpose data=asgmt.data1 out = transpose_ivtt(drop=_label_ _name_ rename=(col1=IVTT));
	var ivtt_c ivtt_tr;
	by personID;
run;
proc transpose data=asgmt.data1 out = transpose_ivtt1(drop=_label_ _name_ rename=(col1=IVTT1));
	var ivtt_c1 ivtt_tr;
	by personID;
run;
proc transpose data=asgmt.data1 out = transpose_ovtt(drop=_label_ _name_ rename=(col1=OVTT));
	var ovtt_c ovtt_tr;
	by personID;
run;
proc transpose data=asgmt.data1 out = transpose_cost(drop=_label_ _name_ rename=(col1=COST));
	var cost_c cost_tr;
	by personID;
run;
proc transpose data=asgmt.data1 out = transpose_cost1(drop=_label_ _name_ rename=(col1=COST1));
	var cost_c1 cost_tr;
	by personID;
run;
/* duplication other variables */
data var_other;
	set asgmt.data1 asgmt.data1;
	drop mode ovtt_c ovtt_tr ivtt_c ivtt_c1 ivtt_tr cost_c cost_c1 cost_tr;
run;
proc sort data=var_other;
	by personid;
run;
/* merge dataset */
data merge1;
	merge transpose_mode var_other transpose_ivtt transpose_ovtt transpose_cost transpose_ivtt1 transpose_cost1;
	by personid;
run;
data asgmt.case_alt1;
	set merge1;
	TOTTIME=ivtt+ovtt;
	TOTTIME1=IVTT1+OVTT;
	ASC=(1-(-1)**_n_)/2; /* alternative-specific constant */
	if mod(_n_, 2)=1 then transfer = 0;
	else transfer=transfer;
	/* set base case */
	array a{6} gender hhsize numveh nworkers nlicdriv hhinc;
		do i =1 to 6;
		a{i}=a{i}*asc;
	end;
	drop i;
run;
